[package]
name = "mlbt"
version = "0.0.13"
authors = ["Andrew Schneider <andjschneider@gmail.com>"]
edition = "2024"

[workspace]
members = [".", "api"]

[dependencies]
anyhow = "1.0.97"
better-panic = "0.3.0"
chrono = "0.4.40"
chrono-tz = "0.10.3"
crossterm = "0.28.1"
crossbeam-channel = "0.5.14"
directories = "6.0.0"
indexmap = "2.0.0"
mlb-api = { path = "api", version = "0.0.10" }
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.2", features = ["full"] }
toml = "0.8.20"
tui = { package = "ratatui", version = "0.29.0" }
