[package]
name = "mlbt"
version = "0.0.12"
authors = ["Andrew Schneider <andjschneider@gmail.com>"]
edition = "2021"

[workspace]
members = [".", "api"]

[dependencies]
anyhow = "1.0.71"
better-panic = "0.3.0"
chrono = "0.4.26"
chrono-tz = "0.8.2"
crossterm = "0.26.1"
crossbeam-channel = "0.5.8"
directories = "5.0.1"
indexmap = "2.0.0"
mlb-api = { path = "api", version = "0.0.10" }
once_cell = "1.18.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
tokio = { version = "1.28.2", features = ["full"] }
toml = "0.7.5"
tui = { package = "ratatui", version = "0.21.0" }
