[package]
name = "mlbt"
version = "0.0.9-alpha1"
authors = ["Andrew Schneider <andjschneider@gmail.com>"]
edition = "2018"

[workspace]
members = [".", "api"]

[dependencies]
mlb-api = {path = "api/", version = "0.0.6-alpha1"}

better-panic = "0.2"
chrono = "0.4"
chrono-tz = "0.5"
crossbeam-channel = "0.5"
crossterm = "0.20"
lazy_static = "1.4.0"
tui = { version = "0.15", default-features = false, features = ["crossterm","serde"] }
