[package]
name = "mlbt"
version = "0.0.11-beta.1"
authors = ["Andrew Schneider <andjschneider@gmail.com>"]
edition = "2021"

[workspace]
members = [".", "api"]

[dependencies]
mlb-api = {path = "api/", version = "0.0.7"}

better-panic = "0.3"
chrono = "0.4"
chrono-tz = "0.6"
crossterm = "0.23"
crossbeam-channel = "0.5"
indexmap = "1.8"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tui = "0.17"
