[package]
name = "mlb-api"
version = "0.0.6-alpha1"
authors = ["Andrew Schneider <andjschneider@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
derive_builder = "0.10"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
mockito = "0.30"
