[package]
name = "mlb-api"
version = "0.0.10"
authors = ["Andrew Schneider <andjschneider@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4.26"
derive_builder = "0.12.0"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"

[dev-dependencies]
mockito = "1.1.0"
once_cell = "1.18.0"
tokio = { version = "1.28.2", features = ["macros"] }
