[package]
name = "mlb-api"
version = "0.0.9"
authors = ["Andrew Schneider <andjschneider@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4.24"
derive_builder = "0.12.0"
reqwest = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"

[dev-dependencies]
mockito = "1.0.2"
once_cell = "1.17.1"
tokio = { version = "1.26.0", features = ["macros"] }
